
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook notebook1;

	private global::Gtk.VBox vbox1;

	private global::Gtk.ScrolledWindow scrolledwindow1;

	private global::Gtk.IconView iconViewPlayers;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label9;

	private global::Gtk.SpinButton spinButtonMaxPlayers;

	private global::Gtk.HButtonBox hbuttonbox1;

	private global::Gtk.Button buttonClearPlayers;

	private global::Gtk.Button buttonRemovePlayers;

	private global::Gtk.Button buttonSavePlayersFile;

	private global::Gtk.Button buttonOpenPlayersFile;

	private global::Gtk.Label label1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView treeViewGames;

	private global::Gtk.HBox hbox4;

	private global::Gtk.HButtonBox hbuttonbox4;

	private global::Gtk.Button buttonOpenGamesFile;

	private global::Gtk.Button buttonNewGame;

	private global::Gtk.Button buttonEditGame;

	private global::Gtk.Button buttonPlayGame;

	private global::Gtk.HButtonBox hbuttonbox2;

	private global::Gtk.Button buttonClearGames;

	private global::Gtk.Button buttonRemoveGames;

	private global::Gtk.Button buttonSaveGamesFile;

	private global::Gtk.Label label2;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Frame frame2;

	private global::Gtk.Alignment GtkAlignment11;

	private global::Gtk.VBox vbox5;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label6;

	private global::Gtk.ComboBoxEntry comboBoxEntryHITTPortName;

	private global::Gtk.HBox hbox3;

	private global::Gtk.CheckButton checkButtonHITTAutoConnect;

	private global::Gtk.HButtonBox hbuttonbox5;

	private global::Gtk.Button buttonHITTRefreshPortNames;

	private global::Gtk.Button buttonHITTConnectDisconnect;

	private global::Gtk.Label GtkLabel14;

	private global::Gtk.Frame frame5;

	private global::Gtk.Alignment GtkAlignment19;

	private global::Gtk.VBox vbox9;

	private global::Gtk.Label labelWiimotesConnected;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Button buttonWiimotesSearch;

	private global::Gtk.Label label15;

	private global::Gtk.SpinButton spinButtonWiimotes;

	private global::Gtk.Label label14;

	private global::Gtk.Button buttonWiimotesDisconnect;

	private global::Gtk.Label GtkLabel24;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Frame frame3;

	private global::Gtk.Alignment GtkAlignment18;

	private global::Gtk.VBox vbox6;

	private global::Gtk.RadioButton radioButtonFullscreen;

	private global::Gtk.HBox hbox9;

	private global::Gtk.RadioButton radioButtonCustomWindowSize;

	private global::Gtk.SpinButton spinButtonWindowWidth;

	private global::Gtk.Label label10;

	private global::Gtk.SpinButton spinButtonWindowHeight;

	private global::Gtk.Label GtkLabel23;

	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment14;

	private global::Gtk.VBox vbox7;

	private global::Gtk.Label labelNetworkAddress;

	private global::Gtk.Label labelNetworkPort;

	private global::Gtk.Label GtkLabel19;

	private global::Gtk.Frame frame4;

	private global::Gtk.Alignment GtkAlignment17;

	private global::Gtk.VBox vbox8;

	private global::Gtk.CheckButton checkbuttonDebugMode;

	private global::Gtk.CheckButton checkButtonSaveData;

	private global::Gtk.HBox hbox6;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Label label11;

	private global::Gtk.SpinButton spinButtonNetworkPlayer;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Label label12;

	private global::Gtk.SpinButton spinButtonNetworkButton;

	private global::Gtk.Button buttonNetworkSend;

	private global::Gtk.Label GtkLabel22;

	private global::Gtk.HButtonBox hbuttonbox3;

	private global::Gtk.Button buttonRevertSettings;

	private global::Gtk.Label label3;

	private global::Gtk.VBox vbox4;

	private global::Gtk.Label label5;

	private global::Gtk.Label label7;

	private global::Gtk.Label label8;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView textViewManual;

	private global::Gtk.Label label4;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Nexus");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(6));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 2;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		this.vbox1.BorderWidth = ((uint)(6));
		// Container child vbox1.Gtk.Box+BoxChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		this.iconViewPlayers = new global::Gtk.IconView ();
		this.iconViewPlayers.CanFocus = true;
		this.iconViewPlayers.Name = "iconViewPlayers";
		this.iconViewPlayers.SelectionMode = ((global::Gtk.SelectionMode)(3));
		this.scrolledwindow1.Add (this.iconViewPlayers);
		this.vbox1.Add (this.scrolledwindow1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.scrolledwindow1]));
		w2.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Max Players");
		this.hbox1.Add (this.label9);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label9]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.spinButtonMaxPlayers = new global::Gtk.SpinButton (2, 100, 1);
		this.spinButtonMaxPlayers.CanFocus = true;
		this.spinButtonMaxPlayers.Name = "spinButtonMaxPlayers";
		this.spinButtonMaxPlayers.Adjustment.PageIncrement = 10;
		this.spinButtonMaxPlayers.ClimbRate = 1;
		this.spinButtonMaxPlayers.Numeric = true;
		this.spinButtonMaxPlayers.Value = 16;
		this.hbox1.Add (this.spinButtonMaxPlayers);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.spinButtonMaxPlayers]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbuttonbox1 = new global::Gtk.HButtonBox ();
		this.hbuttonbox1.Name = "hbuttonbox1";
		this.hbuttonbox1.Spacing = 6;
		this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.buttonClearPlayers = new global::Gtk.Button ();
		this.buttonClearPlayers.CanFocus = true;
		this.buttonClearPlayers.Name = "buttonClearPlayers";
		this.buttonClearPlayers.UseStock = true;
		this.buttonClearPlayers.UseUnderline = true;
		this.buttonClearPlayers.Label = "gtk-clear";
		this.hbuttonbox1.Add (this.buttonClearPlayers);
		global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.buttonClearPlayers]));
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.buttonRemovePlayers = new global::Gtk.Button ();
		this.buttonRemovePlayers.CanFocus = true;
		this.buttonRemovePlayers.Name = "buttonRemovePlayers";
		this.buttonRemovePlayers.UseStock = true;
		this.buttonRemovePlayers.UseUnderline = true;
		this.buttonRemovePlayers.Label = "gtk-remove";
		this.hbuttonbox1.Add (this.buttonRemovePlayers);
		global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.buttonRemovePlayers]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.buttonSavePlayersFile = new global::Gtk.Button ();
		this.buttonSavePlayersFile.CanFocus = true;
		this.buttonSavePlayersFile.Name = "buttonSavePlayersFile";
		this.buttonSavePlayersFile.UseStock = true;
		this.buttonSavePlayersFile.UseUnderline = true;
		this.buttonSavePlayersFile.Label = "gtk-save";
		this.hbuttonbox1.Add (this.buttonSavePlayersFile);
		global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.buttonSavePlayersFile]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.buttonOpenPlayersFile = new global::Gtk.Button ();
		this.buttonOpenPlayersFile.CanFocus = true;
		this.buttonOpenPlayersFile.Name = "buttonOpenPlayersFile";
		this.buttonOpenPlayersFile.UseStock = true;
		this.buttonOpenPlayersFile.UseUnderline = true;
		this.buttonOpenPlayersFile.Label = "gtk-open";
		this.hbuttonbox1.Add (this.buttonOpenPlayersFile);
		global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.buttonOpenPlayersFile]));
		w8.Position = 3;
		w8.Expand = false;
		w8.Fill = false;
		this.hbox1.Add (this.hbuttonbox1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbuttonbox1]));
		w9.Position = 2;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.notebook1.Add (this.vbox1);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Players");
		this.notebook1.SetTabLabel (this.vbox1, this.label1);
		this.label1.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		this.vbox2.BorderWidth = ((uint)(6));
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeViewGames = new global::Gtk.TreeView ();
		this.treeViewGames.CanFocus = true;
		this.treeViewGames.Name = "treeViewGames";
		this.GtkScrolledWindow.Add (this.treeViewGames);
		this.vbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
		w13.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.hbuttonbox4 = new global::Gtk.HButtonBox ();
		this.hbuttonbox4.Name = "hbuttonbox4";
		this.hbuttonbox4.Spacing = 6;
		this.hbuttonbox4.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.buttonOpenGamesFile = new global::Gtk.Button ();
		this.buttonOpenGamesFile.CanFocus = true;
		this.buttonOpenGamesFile.Name = "buttonOpenGamesFile";
		this.buttonOpenGamesFile.UseStock = true;
		this.buttonOpenGamesFile.UseUnderline = true;
		this.buttonOpenGamesFile.Label = "gtk-open";
		this.hbuttonbox4.Add (this.buttonOpenGamesFile);
		global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4[this.buttonOpenGamesFile]));
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.buttonNewGame = new global::Gtk.Button ();
		this.buttonNewGame.CanFocus = true;
		this.buttonNewGame.Name = "buttonNewGame";
		this.buttonNewGame.UseStock = true;
		this.buttonNewGame.UseUnderline = true;
		this.buttonNewGame.Label = "gtk-new";
		this.hbuttonbox4.Add (this.buttonNewGame);
		global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4[this.buttonNewGame]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.buttonEditGame = new global::Gtk.Button ();
		this.buttonEditGame.CanFocus = true;
		this.buttonEditGame.Name = "buttonEditGame";
		this.buttonEditGame.UseStock = true;
		this.buttonEditGame.UseUnderline = true;
		this.buttonEditGame.Label = "gtk-edit";
		this.hbuttonbox4.Add (this.buttonEditGame);
		global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4[this.buttonEditGame]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.buttonPlayGame = new global::Gtk.Button ();
		this.buttonPlayGame.CanFocus = true;
		this.buttonPlayGame.Name = "buttonPlayGame";
		this.buttonPlayGame.UseStock = true;
		this.buttonPlayGame.UseUnderline = true;
		this.buttonPlayGame.Label = "gtk-media-play";
		this.hbuttonbox4.Add (this.buttonPlayGame);
		global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4[this.buttonPlayGame]));
		w17.Position = 3;
		w17.Expand = false;
		w17.Fill = false;
		this.hbox4.Add (this.hbuttonbox4);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbuttonbox4]));
		w18.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.hbuttonbox2 = new global::Gtk.HButtonBox ();
		this.hbuttonbox2.Name = "hbuttonbox2";
		this.hbuttonbox2.Spacing = 6;
		this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.buttonClearGames = new global::Gtk.Button ();
		this.buttonClearGames.CanFocus = true;
		this.buttonClearGames.Name = "buttonClearGames";
		this.buttonClearGames.UseStock = true;
		this.buttonClearGames.UseUnderline = true;
		this.buttonClearGames.Label = "gtk-clear";
		this.hbuttonbox2.Add (this.buttonClearGames);
		global::Gtk.ButtonBox.ButtonBoxChild w19 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.buttonClearGames]));
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.buttonRemoveGames = new global::Gtk.Button ();
		this.buttonRemoveGames.CanFocus = true;
		this.buttonRemoveGames.Name = "buttonRemoveGames";
		this.buttonRemoveGames.UseStock = true;
		this.buttonRemoveGames.UseUnderline = true;
		this.buttonRemoveGames.Label = "gtk-remove";
		this.hbuttonbox2.Add (this.buttonRemoveGames);
		global::Gtk.ButtonBox.ButtonBoxChild w20 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.buttonRemoveGames]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.buttonSaveGamesFile = new global::Gtk.Button ();
		this.buttonSaveGamesFile.CanFocus = true;
		this.buttonSaveGamesFile.Name = "buttonSaveGamesFile";
		this.buttonSaveGamesFile.UseStock = true;
		this.buttonSaveGamesFile.UseUnderline = true;
		this.buttonSaveGamesFile.Label = "gtk-save";
		this.hbuttonbox2.Add (this.buttonSaveGamesFile);
		global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.buttonSaveGamesFile]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		this.hbox4.Add (this.hbuttonbox2);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbuttonbox2]));
		w22.Position = 1;
		w22.Expand = false;
		this.vbox2.Add (this.hbox4);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		this.notebook1.Add (this.vbox2);
		global::Gtk.Notebook.NotebookChild w24 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox2]));
		w24.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Games");
		this.notebook1.SetTabLabel (this.vbox2, this.label2);
		this.label2.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		this.vbox3.BorderWidth = ((uint)(6));
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(4));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment11 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
		this.GtkAlignment11.Name = "GtkAlignment11";
		this.GtkAlignment11.LeftPadding = ((uint)(12));
		// Container child GtkAlignment11.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		this.vbox5.BorderWidth = ((uint)(6));
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Port Name");
		this.hbox2.Add (this.label6);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label6]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.comboBoxEntryHITTPortName = global::Gtk.ComboBoxEntry.NewText ();
		this.comboBoxEntryHITTPortName.Name = "comboBoxEntryHITTPortName";
		this.hbox2.Add (this.comboBoxEntryHITTPortName);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.comboBoxEntryHITTPortName]));
		w26.Position = 1;
		this.vbox5.Add (this.hbox2);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox2]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.checkButtonHITTAutoConnect = new global::Gtk.CheckButton ();
		this.checkButtonHITTAutoConnect.CanFocus = true;
		this.checkButtonHITTAutoConnect.Name = "checkButtonHITTAutoConnect";
		this.checkButtonHITTAutoConnect.Label = global::Mono.Unix.Catalog.GetString ("Automatically connect at startup");
		this.checkButtonHITTAutoConnect.Active = true;
		this.checkButtonHITTAutoConnect.DrawIndicator = true;
		this.checkButtonHITTAutoConnect.UseUnderline = true;
		this.hbox3.Add (this.checkButtonHITTAutoConnect);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.checkButtonHITTAutoConnect]));
		w28.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hbuttonbox5 = new global::Gtk.HButtonBox ();
		this.hbuttonbox5.Name = "hbuttonbox5";
		this.hbuttonbox5.Spacing = 6;
		this.hbuttonbox5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.buttonHITTRefreshPortNames = new global::Gtk.Button ();
		this.buttonHITTRefreshPortNames.CanFocus = true;
		this.buttonHITTRefreshPortNames.Name = "buttonHITTRefreshPortNames";
		this.buttonHITTRefreshPortNames.UseStock = true;
		this.buttonHITTRefreshPortNames.UseUnderline = true;
		this.buttonHITTRefreshPortNames.Label = "gtk-refresh";
		this.hbuttonbox5.Add (this.buttonHITTRefreshPortNames);
		global::Gtk.ButtonBox.ButtonBoxChild w29 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5[this.buttonHITTRefreshPortNames]));
		w29.Expand = false;
		w29.Fill = false;
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.buttonHITTConnectDisconnect = new global::Gtk.Button ();
		this.buttonHITTConnectDisconnect.CanFocus = true;
		this.buttonHITTConnectDisconnect.Name = "buttonHITTConnectDisconnect";
		this.buttonHITTConnectDisconnect.UseStock = true;
		this.buttonHITTConnectDisconnect.UseUnderline = true;
		this.buttonHITTConnectDisconnect.Label = "gtk-connect";
		this.hbuttonbox5.Add (this.buttonHITTConnectDisconnect);
		global::Gtk.ButtonBox.ButtonBoxChild w30 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5[this.buttonHITTConnectDisconnect]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		this.hbox3.Add (this.hbuttonbox5);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hbuttonbox5]));
		w31.Position = 1;
		w31.Expand = false;
		this.vbox5.Add (this.hbox3);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox3]));
		w32.Position = 1;
		w32.Expand = false;
		w32.Fill = false;
		this.GtkAlignment11.Add (this.vbox5);
		this.frame2.Add (this.GtkAlignment11);
		this.GtkLabel14 = new global::Gtk.Label ();
		this.GtkLabel14.Name = "GtkLabel14";
		this.GtkLabel14.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>H-ITT Base Station</b>");
		this.GtkLabel14.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel14;
		this.vbox3.Add (this.frame2);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.frame2]));
		w35.Position = 0;
		w35.Expand = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame5 = new global::Gtk.Frame ();
		this.frame5.Name = "frame5";
		this.frame5.ShadowType = ((global::Gtk.ShadowType)(4));
		// Container child frame5.Gtk.Container+ContainerChild
		this.GtkAlignment19 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
		this.GtkAlignment19.Name = "GtkAlignment19";
		this.GtkAlignment19.LeftPadding = ((uint)(12));
		// Container child GtkAlignment19.Gtk.Container+ContainerChild
		this.vbox9 = new global::Gtk.VBox ();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		this.vbox9.BorderWidth = ((uint)(6));
		// Container child vbox9.Gtk.Box+BoxChild
		this.labelWiimotesConnected = new global::Gtk.Label ();
		this.labelWiimotesConnected.Name = "labelWiimotesConnected";
		this.labelWiimotesConnected.Xalign = 0f;
		this.labelWiimotesConnected.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Connected</b>: 0");
		this.labelWiimotesConnected.UseMarkup = true;
		this.vbox9.Add (this.labelWiimotesConnected);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.labelWiimotesConnected]));
		w36.Position = 0;
		w36.Expand = false;
		w36.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.buttonWiimotesSearch = new global::Gtk.Button ();
		this.buttonWiimotesSearch.CanFocus = true;
		this.buttonWiimotesSearch.Name = "buttonWiimotesSearch";
		this.buttonWiimotesSearch.UseUnderline = true;
		// Container child buttonWiimotesSearch.Gtk.Container+ContainerChild
		global::Gtk.Alignment w37 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w38 = new global::Gtk.HBox ();
		w38.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w39 = new global::Gtk.Image ();
		w39.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Menu);
		w38.Add (w39);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w41 = new global::Gtk.Label ();
		w41.LabelProp = global::Mono.Unix.Catalog.GetString ("_Search");
		w41.UseUnderline = true;
		w38.Add (w41);
		w37.Add (w38);
		this.buttonWiimotesSearch.Add (w37);
		this.hbox10.Add (this.buttonWiimotesSearch);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.buttonWiimotesSearch]));
		w45.Position = 0;
		w45.Expand = false;
		w45.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("for");
		this.hbox10.Add (this.label15);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label15]));
		w46.Position = 1;
		w46.Expand = false;
		w46.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.spinButtonWiimotes = new global::Gtk.SpinButton (5, 30, 1);
		this.spinButtonWiimotes.CanFocus = true;
		this.spinButtonWiimotes.Name = "spinButtonWiimotes";
		this.spinButtonWiimotes.Adjustment.PageIncrement = 10;
		this.spinButtonWiimotes.ClimbRate = 1;
		this.spinButtonWiimotes.Numeric = true;
		this.spinButtonWiimotes.Value = 5;
		this.hbox10.Add (this.spinButtonWiimotes);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.spinButtonWiimotes]));
		w47.Position = 2;
		w47.Expand = false;
		w47.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("second(s)");
		this.hbox10.Add (this.label14);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label14]));
		w48.Position = 3;
		w48.Expand = false;
		w48.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.buttonWiimotesDisconnect = new global::Gtk.Button ();
		this.buttonWiimotesDisconnect.Sensitive = false;
		this.buttonWiimotesDisconnect.CanFocus = true;
		this.buttonWiimotesDisconnect.Name = "buttonWiimotesDisconnect";
		this.buttonWiimotesDisconnect.UseStock = true;
		this.buttonWiimotesDisconnect.UseUnderline = true;
		this.buttonWiimotesDisconnect.Label = "gtk-disconnect";
		this.hbox10.Add (this.buttonWiimotesDisconnect);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.buttonWiimotesDisconnect]));
		w49.PackType = ((global::Gtk.PackType)(1));
		w49.Position = 4;
		w49.Expand = false;
		w49.Fill = false;
		this.vbox9.Add (this.hbox10);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox10]));
		w50.Position = 1;
		w50.Expand = false;
		w50.Fill = false;
		this.GtkAlignment19.Add (this.vbox9);
		this.frame5.Add (this.GtkAlignment19);
		this.GtkLabel24 = new global::Gtk.Label ();
		this.GtkLabel24.Name = "GtkLabel24";
		this.GtkLabel24.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Wiimotes</b>");
		this.GtkLabel24.UseMarkup = true;
		this.frame5.LabelWidget = this.GtkLabel24;
		this.vbox3.Add (this.frame5);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.frame5]));
		w53.Position = 1;
		w53.Expand = false;
		w53.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame ();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(4));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment18 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
		this.GtkAlignment18.Name = "GtkAlignment18";
		this.GtkAlignment18.LeftPadding = ((uint)(12));
		// Container child GtkAlignment18.Gtk.Container+ContainerChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		this.vbox6.BorderWidth = ((uint)(6));
		// Container child vbox6.Gtk.Box+BoxChild
		this.radioButtonFullscreen = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Full screen"));
		this.radioButtonFullscreen.CanFocus = true;
		this.radioButtonFullscreen.Name = "radioButtonFullscreen";
		this.radioButtonFullscreen.Active = true;
		this.radioButtonFullscreen.DrawIndicator = true;
		this.radioButtonFullscreen.UseUnderline = true;
		this.radioButtonFullscreen.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.vbox6.Add (this.radioButtonFullscreen);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.radioButtonFullscreen]));
		w54.Position = 0;
		w54.Expand = false;
		w54.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.radioButtonCustomWindowSize = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Custom window size"));
		this.radioButtonCustomWindowSize.CanFocus = true;
		this.radioButtonCustomWindowSize.Name = "radioButtonCustomWindowSize";
		this.radioButtonCustomWindowSize.DrawIndicator = true;
		this.radioButtonCustomWindowSize.UseUnderline = true;
		this.radioButtonCustomWindowSize.Group = this.radioButtonFullscreen.Group;
		this.hbox9.Add (this.radioButtonCustomWindowSize);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.radioButtonCustomWindowSize]));
		w55.Position = 0;
		w55.Expand = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.spinButtonWindowWidth = new global::Gtk.SpinButton (0, 9999, 1);
		this.spinButtonWindowWidth.Sensitive = false;
		this.spinButtonWindowWidth.CanFocus = true;
		this.spinButtonWindowWidth.Name = "spinButtonWindowWidth";
		this.spinButtonWindowWidth.Adjustment.PageIncrement = 10;
		this.spinButtonWindowWidth.ClimbRate = 1;
		this.spinButtonWindowWidth.Numeric = true;
		this.spinButtonWindowWidth.Value = 1024;
		this.hbox9.Add (this.spinButtonWindowWidth);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.spinButtonWindowWidth]));
		w56.Position = 1;
		w56.Expand = false;
		w56.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("x");
		this.hbox9.Add (this.label10);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label10]));
		w57.Position = 2;
		w57.Expand = false;
		w57.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.spinButtonWindowHeight = new global::Gtk.SpinButton (0, 9999, 1);
		this.spinButtonWindowHeight.Sensitive = false;
		this.spinButtonWindowHeight.CanFocus = true;
		this.spinButtonWindowHeight.Name = "spinButtonWindowHeight";
		this.spinButtonWindowHeight.Adjustment.PageIncrement = 10;
		this.spinButtonWindowHeight.ClimbRate = 1;
		this.spinButtonWindowHeight.Numeric = true;
		this.spinButtonWindowHeight.Value = 768;
		this.hbox9.Add (this.spinButtonWindowHeight);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.spinButtonWindowHeight]));
		w58.Position = 3;
		w58.Expand = false;
		w58.Fill = false;
		this.vbox6.Add (this.hbox9);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox9]));
		w59.Position = 1;
		w59.Expand = false;
		w59.Fill = false;
		this.GtkAlignment18.Add (this.vbox6);
		this.frame3.Add (this.GtkAlignment18);
		this.GtkLabel23 = new global::Gtk.Label ();
		this.GtkLabel23.Name = "GtkLabel23";
		this.GtkLabel23.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Graphics</b>");
		this.GtkLabel23.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel23;
		this.hbox5.Add (this.frame3);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.frame3]));
		w62.Position = 0;
		w62.Expand = false;
		w62.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(4));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment14 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
		this.GtkAlignment14.Name = "GtkAlignment14";
		this.GtkAlignment14.LeftPadding = ((uint)(12));
		// Container child GtkAlignment14.Gtk.Container+ContainerChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		this.vbox7.BorderWidth = ((uint)(6));
		// Container child vbox7.Gtk.Box+BoxChild
		this.labelNetworkAddress = new global::Gtk.Label ();
		this.labelNetworkAddress.Name = "labelNetworkAddress";
		this.labelNetworkAddress.Xalign = 0f;
		this.labelNetworkAddress.LabelProp = global::Mono.Unix.Catalog.GetString ("<span weight=\"bold\" color=\"#333333\">IP Address</span>: 127.0.0.1");
		this.labelNetworkAddress.UseMarkup = true;
		this.vbox7.Add (this.labelNetworkAddress);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.labelNetworkAddress]));
		w63.Position = 0;
		w63.Expand = false;
		w63.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.labelNetworkPort = new global::Gtk.Label ();
		this.labelNetworkPort.Name = "labelNetworkPort";
		this.labelNetworkPort.Xalign = 0f;
		this.labelNetworkPort.LabelProp = global::Mono.Unix.Catalog.GetString ("<span weight=\"bold\" color=\"#333333\">Port</span>: 0");
		this.labelNetworkPort.UseMarkup = true;
		this.vbox7.Add (this.labelNetworkPort);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.labelNetworkPort]));
		w64.Position = 1;
		w64.Expand = false;
		w64.Fill = false;
		this.GtkAlignment14.Add (this.vbox7);
		this.frame1.Add (this.GtkAlignment14);
		this.GtkLabel19 = new global::Gtk.Label ();
		this.GtkLabel19.Name = "GtkLabel19";
		this.GtkLabel19.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Network</b>");
		this.GtkLabel19.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel19;
		this.hbox5.Add (this.frame1);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.frame1]));
		w67.PackType = ((global::Gtk.PackType)(1));
		w67.Position = 1;
		w67.Expand = false;
		w67.Fill = false;
		this.vbox3.Add (this.hbox5);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox5]));
		w68.Position = 2;
		w68.Expand = false;
		w68.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame ();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(4));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment17 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
		this.GtkAlignment17.Name = "GtkAlignment17";
		this.GtkAlignment17.LeftPadding = ((uint)(12));
		// Container child GtkAlignment17.Gtk.Container+ContainerChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		this.vbox8.BorderWidth = ((uint)(6));
		// Container child vbox8.Gtk.Box+BoxChild
		this.checkbuttonDebugMode = new global::Gtk.CheckButton ();
		this.checkbuttonDebugMode.CanFocus = true;
		this.checkbuttonDebugMode.Name = "checkbuttonDebugMode";
		this.checkbuttonDebugMode.Label = global::Mono.Unix.Catalog.GetString ("Enable debug mode for games");
		this.checkbuttonDebugMode.Active = true;
		this.checkbuttonDebugMode.DrawIndicator = true;
		this.checkbuttonDebugMode.UseUnderline = true;
		this.vbox8.Add (this.checkbuttonDebugMode);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.checkbuttonDebugMode]));
		w69.Position = 0;
		w69.Expand = false;
		w69.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.checkButtonSaveData = new global::Gtk.CheckButton ();
		this.checkButtonSaveData.CanFocus = true;
		this.checkButtonSaveData.Name = "checkButtonSaveData";
		this.checkButtonSaveData.Label = global::Mono.Unix.Catalog.GetString ("Require game data to be recorded");
		this.checkButtonSaveData.Active = true;
		this.checkButtonSaveData.DrawIndicator = true;
		this.checkButtonSaveData.UseUnderline = true;
		this.vbox8.Add (this.checkButtonSaveData);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.checkButtonSaveData]));
		w70.Position = 1;
		w70.Expand = false;
		w70.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 12;
		// Container child hbox6.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Player");
		this.hbox7.Add (this.label11);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label11]));
		w71.Position = 0;
		w71.Expand = false;
		w71.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.spinButtonNetworkPlayer = new global::Gtk.SpinButton (1, 256, 1);
		this.spinButtonNetworkPlayer.CanFocus = true;
		this.spinButtonNetworkPlayer.Name = "spinButtonNetworkPlayer";
		this.spinButtonNetworkPlayer.Adjustment.PageIncrement = 10;
		this.spinButtonNetworkPlayer.ClimbRate = 1;
		this.spinButtonNetworkPlayer.Numeric = true;
		this.spinButtonNetworkPlayer.Value = 1;
		this.hbox7.Add (this.spinButtonNetworkPlayer);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.spinButtonNetworkPlayer]));
		w72.Position = 1;
		w72.Expand = false;
		w72.Fill = false;
		this.hbox6.Add (this.hbox7);
		global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.hbox7]));
		w73.Position = 0;
		w73.Expand = false;
		w73.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Button");
		this.hbox8.Add (this.label12);
		global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label12]));
		w74.Position = 0;
		w74.Expand = false;
		w74.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.spinButtonNetworkButton = new global::Gtk.SpinButton (1, 10, 1);
		this.spinButtonNetworkButton.CanFocus = true;
		this.spinButtonNetworkButton.Name = "spinButtonNetworkButton";
		this.spinButtonNetworkButton.Adjustment.PageIncrement = 10;
		this.spinButtonNetworkButton.ClimbRate = 1;
		this.spinButtonNetworkButton.Numeric = true;
		this.spinButtonNetworkButton.Value = 1;
		this.hbox8.Add (this.spinButtonNetworkButton);
		global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.spinButtonNetworkButton]));
		w75.Position = 1;
		w75.Expand = false;
		w75.Fill = false;
		this.hbox6.Add (this.hbox8);
		global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.hbox8]));
		w76.Position = 1;
		w76.Expand = false;
		w76.Fill = false;
		w76.Padding = ((uint)(6));
		// Container child hbox6.Gtk.Box+BoxChild
		this.buttonNetworkSend = new global::Gtk.Button ();
		this.buttonNetworkSend.CanFocus = true;
		this.buttonNetworkSend.Name = "buttonNetworkSend";
		this.buttonNetworkSend.UseUnderline = true;
		// Container child buttonNetworkSend.Gtk.Container+ContainerChild
		global::Gtk.Alignment w77 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w78 = new global::Gtk.HBox ();
		w78.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w79 = new global::Gtk.Image ();
		w79.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-network", global::Gtk.IconSize.Button);
		w78.Add (w79);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w81 = new global::Gtk.Label ();
		w81.LabelProp = global::Mono.Unix.Catalog.GetString ("_Send");
		w81.UseUnderline = true;
		w78.Add (w81);
		w77.Add (w78);
		this.buttonNetworkSend.Add (w77);
		this.hbox6.Add (this.buttonNetworkSend);
		global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.buttonNetworkSend]));
		w85.Position = 2;
		w85.Expand = false;
		w85.Fill = false;
		this.vbox8.Add (this.hbox6);
		global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox6]));
		w86.Position = 2;
		w86.Expand = false;
		w86.Fill = false;
		this.GtkAlignment17.Add (this.vbox8);
		this.frame4.Add (this.GtkAlignment17);
		this.GtkLabel22 = new global::Gtk.Label ();
		this.GtkLabel22.Name = "GtkLabel22";
		this.GtkLabel22.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Testing</b>");
		this.GtkLabel22.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel22;
		this.vbox3.Add (this.frame4);
		global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.frame4]));
		w89.Position = 3;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbuttonbox3 = new global::Gtk.HButtonBox ();
		this.hbuttonbox3.Name = "hbuttonbox3";
		this.hbuttonbox3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this.buttonRevertSettings = new global::Gtk.Button ();
		this.buttonRevertSettings.CanFocus = true;
		this.buttonRevertSettings.Name = "buttonRevertSettings";
		this.buttonRevertSettings.UseStock = true;
		this.buttonRevertSettings.UseUnderline = true;
		this.buttonRevertSettings.Label = "gtk-revert-to-saved";
		this.hbuttonbox3.Add (this.buttonRevertSettings);
		global::Gtk.ButtonBox.ButtonBoxChild w90 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.buttonRevertSettings]));
		w90.Expand = false;
		w90.Fill = false;
		this.vbox3.Add (this.hbuttonbox3);
		global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbuttonbox3]));
		w91.PackType = ((global::Gtk.PackType)(1));
		w91.Position = 4;
		w91.Expand = false;
		w91.Fill = false;
		this.notebook1.Add (this.vbox3);
		global::Gtk.Notebook.NotebookChild w92 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox3]));
		w92.Position = 2;
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Settings");
		this.notebook1.SetTabLabel (this.vbox3, this.label3);
		this.label3.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		this.vbox4.BorderWidth = ((uint)(6));
		// Container child vbox4.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("<span size=\"x-large\" weight=\"bold\">Nexus 1.0</span>");
		this.label5.UseMarkup = true;
		this.vbox4.Add (this.label5);
		global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label5]));
		w93.Position = 0;
		w93.Expand = false;
		w93.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Written by Michael Hansen");
		this.vbox4.Add (this.label7);
		global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label7]));
		w94.Position = 1;
		w94.Expand = false;
		w94.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Rob Goldstone's Percepts and Concepts Lab, IU 2009");
		this.vbox4.Add (this.label8);
		global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label8]));
		w95.Position = 2;
		w95.Expand = false;
		w95.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textViewManual = new global::Gtk.TextView ();
		this.textViewManual.CanFocus = true;
		this.textViewManual.Name = "textViewManual";
		this.GtkScrolledWindow1.Add (this.textViewManual);
		this.vbox4.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.GtkScrolledWindow1]));
		w97.Position = 3;
		this.notebook1.Add (this.vbox4);
		global::Gtk.Notebook.NotebookChild w98 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox4]));
		w98.Position = 3;
		// Notebook tab
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("About");
		this.notebook1.SetTabLabel (this.vbox4, this.label4);
		this.label4.ShowAll ();
		this.Add (this.notebook1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 803;
		this.DefaultHeight = 532;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.buttonClearPlayers.Clicked += new global::System.EventHandler (this.OnButtonClearPlayersClicked);
		this.buttonRemovePlayers.Clicked += new global::System.EventHandler (this.OnButtonRemovePlayersClicked);
		this.buttonSavePlayersFile.Clicked += new global::System.EventHandler (this.OnButtonSavePlayersFileClicked);
		this.buttonOpenPlayersFile.Clicked += new global::System.EventHandler (this.OnButtonOpenPlayersFileClicked);
		this.buttonOpenGamesFile.Clicked += new global::System.EventHandler (this.OnButtonOpenGamesFileClicked);
		this.buttonNewGame.Clicked += new global::System.EventHandler (this.OnButtonNewGameClicked);
		this.buttonEditGame.Clicked += new global::System.EventHandler (this.OnButtonEditGameClicked);
		this.buttonPlayGame.Clicked += new global::System.EventHandler (this.OnButtonPlayGameClicked);
		this.buttonClearGames.Clicked += new global::System.EventHandler (this.OnButtonClearGamesClicked);
		this.buttonRemoveGames.Clicked += new global::System.EventHandler (this.OnButtonRemoveGamesClicked);
		this.buttonSaveGamesFile.Clicked += new global::System.EventHandler (this.OnButtonSaveGamesFileClicked);
		this.buttonHITTRefreshPortNames.Clicked += new global::System.EventHandler (this.OnButtonHITTRefreshPortNamesClicked);
		this.buttonHITTConnectDisconnect.Clicked += new global::System.EventHandler (this.OnButtonHITTConnectDisconnectClicked);
		this.buttonWiimotesSearch.Clicked += new global::System.EventHandler (this.OnButtonWiimotesSearchClicked);
		this.buttonWiimotesDisconnect.Clicked += new global::System.EventHandler (this.OnButtonWiimotesDisconnectClicked);
		this.radioButtonCustomWindowSize.Toggled += new global::System.EventHandler (this.OnRadioButtonCustomResolutionToggled);
		this.buttonNetworkSend.Clicked += new global::System.EventHandler (this.OnButtonNetworkSendClicked);
		this.buttonRevertSettings.Clicked += new global::System.EventHandler (this.OnButtonRevertSettingsClicked);
	}
}
