
// This file has been generated by the GUI designer. Do not modify.
namespace Nexus
{
	public partial class DialogNewGame
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label2;

		private global::Gtk.ComboBox comboBoxGame;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label8;

		private global::Gtk.Entry entryGameDescription;

		private global::Gtk.Notebook noteBookGameSettings;

		private global::Gtk.Label label5;

		private global::Gtk.Label label1;

		private global::Gtk.Table tablePixel;

		private global::Gtk.ComboBox comboBoxPixelInitialState;

		private global::Gtk.ComboBox comboBoxPixelPlayerSort;

		private global::Gtk.Label label10;

		private global::Gtk.Label label6;

		private global::Gtk.Label label7;

		private global::Gtk.Label label9;

		private global::Gtk.SpinButton spinButtonPixelMaxSize;

		private global::Gtk.Label label3;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox3;

		private global::Gtk.CheckButton checkBoxFlatlandCustomBoardSize;

		private global::Gtk.SpinButton spinButtonFlatlandBoardSize;

		private global::Gtk.Button buttonFlatlandEditFixedTiles;

		private global::Gtk.HBox hbox4;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Label label11;

		private global::Gtk.ComboBox comboBoxFlatlandCollisionBehavior;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Label label28;

		private global::Gtk.ComboBox comboBoxFlatlandGameType;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeViewFlatlandTeams;

		private global::Gtk.HButtonBox hbuttonbox2;

		private global::Gtk.Button buttonFlatlandClearTeams;

		private global::Gtk.Button buttonFlatlandRemoveTeam;

		private global::Gtk.Button buttonFlatlandAddTeam;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.Label label4;

		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label13;

		private global::Gtk.SpinButton spinButtonGroupSumFirstRoundSeconds;

		private global::Gtk.Label label14;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label15;

		private global::Gtk.SpinButton spinButtonGroupSumRoundSeconds;

		private global::Gtk.Label label16;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label label17;

		private global::Gtk.SpinButton spinButtonGroupSumRangeStart;

		private global::Gtk.Label label18;

		private global::Gtk.SpinButton spinButtonGroupSumRangeEnd;

		private global::Gtk.Label label19;

		private global::Gtk.CheckButton checkButtonGroupSumNumericFeedback;

		private global::Gtk.CheckButton checkbuttonGroupSumPreviousInput;

		private global::Gtk.Label label12;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Table table1;

		private global::Gtk.Label label21;

		private global::Gtk.Label label22;

		private global::Gtk.Label label23;

		private global::Gtk.Label label24;

		private global::Gtk.SpinButton spinButtonForagerFoodRate;

		private global::Gtk.SpinButton spinButtonForagerGameMinutes;

		private global::Gtk.SpinButton spinButtonForagerPlots;

		private global::Gtk.SpinButton spinButtonForagerTravelTime;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label label25;

		private global::Gtk.ComboBox comboBoxForagerProbabilitySet;

		private global::Gtk.Button buttonForagerAddProbabilitySet;

		private global::Gtk.Button buttonForagerRemoveProbabilitySet;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Label label26;

		private global::Gtk.SpinButton spinButtonForagerProbabilityShiftMinutes;

		private global::Gtk.Label label27;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView treeViewForagerProbabilities;

		private global::Gtk.Label label20;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Nexus.DialogNewGame
			this.Name = "Nexus.DialogNewGame";
			this.Title = global::Mono.Unix.Catalog.GetString ("New Game");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-new", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Internal child Nexus.DialogNewGame.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(6));
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Game");
			this.hbox1.Add (this.label2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.comboBoxGame = global::Gtk.ComboBox.NewText ();
			this.comboBoxGame.AppendText (global::Mono.Unix.Catalog.GetString ("Select"));
			this.comboBoxGame.AppendText (global::Mono.Unix.Catalog.GetString ("Pixel"));
			this.comboBoxGame.AppendText (global::Mono.Unix.Catalog.GetString ("Flatland"));
			this.comboBoxGame.AppendText (global::Mono.Unix.Catalog.GetString ("Group Sum"));
			this.comboBoxGame.AppendText (global::Mono.Unix.Catalog.GetString ("Forager"));
			this.comboBoxGame.Name = "comboBoxGame";
			this.comboBoxGame.Active = 0;
			this.hbox1.Add (this.comboBoxGame);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.comboBoxGame]));
			w3.Position = 1;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Description");
			this.hbox2.Add (this.label8);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label8]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entryGameDescription = new global::Gtk.Entry ();
			this.entryGameDescription.Sensitive = false;
			this.entryGameDescription.CanFocus = true;
			this.entryGameDescription.Name = "entryGameDescription";
			this.entryGameDescription.Text = global::Mono.Unix.Catalog.GetString ("New Game");
			this.entryGameDescription.IsEditable = true;
			this.entryGameDescription.InvisibleChar = '●';
			this.hbox2.Add (this.entryGameDescription);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.entryGameDescription]));
			w6.Position = 1;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.noteBookGameSettings = new global::Gtk.Notebook ();
			this.noteBookGameSettings.CanFocus = true;
			this.noteBookGameSettings.Name = "noteBookGameSettings";
			this.noteBookGameSettings.CurrentPage = 2;
			this.noteBookGameSettings.ShowBorder = false;
			this.noteBookGameSettings.ShowTabs = false;
			// Container child noteBookGameSettings.Gtk.Notebook+NotebookChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Select a game from the list above");
			this.noteBookGameSettings.Add (this.label5);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Default");
			this.noteBookGameSettings.SetTabLabel (this.label5, this.label1);
			this.label1.ShowAll ();
			// Container child noteBookGameSettings.Gtk.Notebook+NotebookChild
			this.tablePixel = new global::Gtk.Table (((uint)(4)), ((uint)(3)), false);
			this.tablePixel.Name = "tablePixel";
			this.tablePixel.RowSpacing = ((uint)(6));
			this.tablePixel.ColumnSpacing = ((uint)(6));
			// Container child tablePixel.Gtk.Table+TableChild
			this.comboBoxPixelInitialState = global::Gtk.ComboBox.NewText ();
			this.comboBoxPixelInitialState.AppendText (global::Mono.Unix.Catalog.GetString ("Random"));
			this.comboBoxPixelInitialState.AppendText (global::Mono.Unix.Catalog.GetString ("On"));
			this.comboBoxPixelInitialState.AppendText (global::Mono.Unix.Catalog.GetString ("Off"));
			this.comboBoxPixelInitialState.Name = "comboBoxPixelInitialState";
			this.comboBoxPixelInitialState.Active = 0;
			this.tablePixel.Add (this.comboBoxPixelInitialState);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tablePixel[this.comboBoxPixelInitialState]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tablePixel.Gtk.Table+TableChild
			this.comboBoxPixelPlayerSort = global::Gtk.ComboBox.NewText ();
			this.comboBoxPixelPlayerSort.AppendText (global::Mono.Unix.Catalog.GetString ("Random"));
			this.comboBoxPixelPlayerSort.AppendText (global::Mono.Unix.Catalog.GetString ("Clustered"));
			this.comboBoxPixelPlayerSort.AppendText (global::Mono.Unix.Catalog.GetString ("Diffuse"));
			this.comboBoxPixelPlayerSort.Name = "comboBoxPixelPlayerSort";
			this.comboBoxPixelPlayerSort.Active = 0;
			this.tablePixel.Add (this.comboBoxPixelPlayerSort);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tablePixel[this.comboBoxPixelPlayerSort]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tablePixel.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 0f;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Initial Pixel State");
			this.tablePixel.Add (this.label10);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tablePixel[this.label10]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tablePixel.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 0f;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Fixed Pixels");
			this.tablePixel.Add (this.label6);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tablePixel[this.label6]));
			w12.TopAttach = ((uint)(3));
			w12.BottomAttach = ((uint)(4));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tablePixel.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 0f;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Player Sort");
			this.tablePixel.Add (this.label7);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tablePixel[this.label7]));
			w13.TopAttach = ((uint)(2));
			w13.BottomAttach = ((uint)(3));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tablePixel.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 0f;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Max Size");
			this.tablePixel.Add (this.label9);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tablePixel[this.label9]));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tablePixel.Gtk.Table+TableChild
			this.spinButtonPixelMaxSize = new global::Gtk.SpinButton (1, 100, 1);
			this.spinButtonPixelMaxSize.CanFocus = true;
			this.spinButtonPixelMaxSize.Name = "spinButtonPixelMaxSize";
			this.spinButtonPixelMaxSize.Adjustment.PageIncrement = 10;
			this.spinButtonPixelMaxSize.ClimbRate = 1;
			this.spinButtonPixelMaxSize.Numeric = true;
			this.spinButtonPixelMaxSize.Value = 12;
			this.tablePixel.Add (this.spinButtonPixelMaxSize);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tablePixel[this.spinButtonPixelMaxSize]));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			this.noteBookGameSettings.Add (this.tablePixel);
			global::Gtk.Notebook.NotebookChild w16 = ((global::Gtk.Notebook.NotebookChild)(this.noteBookGameSettings[this.tablePixel]));
			w16.Position = 1;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Pixel");
			this.noteBookGameSettings.SetTabLabel (this.tablePixel, this.label3);
			this.label3.ShowAll ();
			// Container child noteBookGameSettings.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.checkBoxFlatlandCustomBoardSize = new global::Gtk.CheckButton ();
			this.checkBoxFlatlandCustomBoardSize.CanFocus = true;
			this.checkBoxFlatlandCustomBoardSize.Name = "checkBoxFlatlandCustomBoardSize";
			this.checkBoxFlatlandCustomBoardSize.Label = global::Mono.Unix.Catalog.GetString ("Custom board size");
			this.checkBoxFlatlandCustomBoardSize.DrawIndicator = true;
			this.checkBoxFlatlandCustomBoardSize.UseUnderline = true;
			this.hbox3.Add (this.checkBoxFlatlandCustomBoardSize);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.checkBoxFlatlandCustomBoardSize]));
			w17.Position = 0;
			w17.Expand = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.spinButtonFlatlandBoardSize = new global::Gtk.SpinButton (1, 100, 1);
			this.spinButtonFlatlandBoardSize.Sensitive = false;
			this.spinButtonFlatlandBoardSize.CanFocus = true;
			this.spinButtonFlatlandBoardSize.Name = "spinButtonFlatlandBoardSize";
			this.spinButtonFlatlandBoardSize.Adjustment.PageIncrement = 10;
			this.spinButtonFlatlandBoardSize.ClimbRate = 1;
			this.spinButtonFlatlandBoardSize.Numeric = true;
			this.spinButtonFlatlandBoardSize.Value = 8;
			this.hbox3.Add (this.spinButtonFlatlandBoardSize);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.spinButtonFlatlandBoardSize]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonFlatlandEditFixedTiles = new global::Gtk.Button ();
			this.buttonFlatlandEditFixedTiles.Sensitive = false;
			this.buttonFlatlandEditFixedTiles.CanFocus = true;
			this.buttonFlatlandEditFixedTiles.Name = "buttonFlatlandEditFixedTiles";
			this.buttonFlatlandEditFixedTiles.UseUnderline = true;
			// Container child buttonFlatlandEditFixedTiles.Gtk.Container+ContainerChild
			global::Gtk.Alignment w19 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w20 = new global::Gtk.HBox ();
			w20.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w21 = new global::Gtk.Image ();
			w21.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Button);
			w20.Add (w21);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w23 = new global::Gtk.Label ();
			w23.LabelProp = global::Mono.Unix.Catalog.GetString ("_Edit Fixed Tiles");
			w23.UseUnderline = true;
			w20.Add (w23);
			w19.Add (w20);
			this.buttonFlatlandEditFixedTiles.Add (w19);
			this.hbox3.Add (this.buttonFlatlandEditFixedTiles);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.buttonFlatlandEditFixedTiles]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 0f;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Collision Behavior");
			this.hbox9.Add (this.label11);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label11]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.comboBoxFlatlandCollisionBehavior = global::Gtk.ComboBox.NewText ();
			this.comboBoxFlatlandCollisionBehavior.AppendText (global::Mono.Unix.Catalog.GetString ("Allow"));
			this.comboBoxFlatlandCollisionBehavior.AppendText (global::Mono.Unix.Catalog.GetString ("Block"));
			this.comboBoxFlatlandCollisionBehavior.Name = "comboBoxFlatlandCollisionBehavior";
			this.comboBoxFlatlandCollisionBehavior.Active = 0;
			this.hbox9.Add (this.comboBoxFlatlandCollisionBehavior);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.comboBoxFlatlandCollisionBehavior]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			this.hbox4.Add (this.hbox9);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbox9]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label28 = new global::Gtk.Label ();
			this.label28.Name = "label28";
			this.label28.LabelProp = global::Mono.Unix.Catalog.GetString ("Game Type");
			this.hbox10.Add (this.label28);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label28]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.comboBoxFlatlandGameType = global::Gtk.ComboBox.NewText ();
			this.comboBoxFlatlandGameType.AppendText (global::Mono.Unix.Catalog.GetString ("Normal"));
			this.comboBoxFlatlandGameType.AppendText (global::Mono.Unix.Catalog.GetString ("NQueens"));
			this.comboBoxFlatlandGameType.AppendText (global::Mono.Unix.Catalog.GetString ("OnePrey"));
			this.comboBoxFlatlandGameType.Name = "comboBoxFlatlandGameType";
			this.comboBoxFlatlandGameType.Active = 0;
			this.hbox10.Add (this.comboBoxFlatlandGameType);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.comboBoxFlatlandGameType]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			this.hbox4.Add (this.hbox10);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbox10]));
			w34.PackType = ((global::Gtk.PackType)(1));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeViewFlatlandTeams = new global::Gtk.TreeView ();
			this.treeViewFlatlandTeams.CanFocus = true;
			this.treeViewFlatlandTeams.Name = "treeViewFlatlandTeams";
			this.GtkScrolledWindow.Add (this.treeViewFlatlandTeams);
			this.vbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
			w37.Position = 2;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.Spacing = 6;
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonFlatlandClearTeams = new global::Gtk.Button ();
			this.buttonFlatlandClearTeams.CanFocus = true;
			this.buttonFlatlandClearTeams.Name = "buttonFlatlandClearTeams";
			this.buttonFlatlandClearTeams.UseStock = true;
			this.buttonFlatlandClearTeams.UseUnderline = true;
			this.buttonFlatlandClearTeams.Label = "gtk-clear";
			this.hbuttonbox2.Add (this.buttonFlatlandClearTeams);
			global::Gtk.ButtonBox.ButtonBoxChild w38 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.buttonFlatlandClearTeams]));
			w38.Expand = false;
			w38.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonFlatlandRemoveTeam = new global::Gtk.Button ();
			this.buttonFlatlandRemoveTeam.CanFocus = true;
			this.buttonFlatlandRemoveTeam.Name = "buttonFlatlandRemoveTeam";
			this.buttonFlatlandRemoveTeam.UseStock = true;
			this.buttonFlatlandRemoveTeam.UseUnderline = true;
			this.buttonFlatlandRemoveTeam.Label = "gtk-remove";
			this.hbuttonbox2.Add (this.buttonFlatlandRemoveTeam);
			global::Gtk.ButtonBox.ButtonBoxChild w39 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.buttonFlatlandRemoveTeam]));
			w39.Position = 1;
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.buttonFlatlandAddTeam = new global::Gtk.Button ();
			this.buttonFlatlandAddTeam.CanFocus = true;
			this.buttonFlatlandAddTeam.Name = "buttonFlatlandAddTeam";
			this.buttonFlatlandAddTeam.UseStock = true;
			this.buttonFlatlandAddTeam.UseUnderline = true;
			this.buttonFlatlandAddTeam.Label = "gtk-add";
			this.hbuttonbox2.Add (this.buttonFlatlandAddTeam);
			global::Gtk.ButtonBox.ButtonBoxChild w40 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.buttonFlatlandAddTeam]));
			w40.Position = 2;
			w40.Expand = false;
			w40.Fill = false;
			this.vbox3.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbuttonbox2]));
			w41.Position = 3;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox3.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hseparator1]));
			w42.Position = 4;
			w42.Expand = false;
			w42.Fill = false;
			this.noteBookGameSettings.Add (this.vbox3);
			global::Gtk.Notebook.NotebookChild w43 = ((global::Gtk.Notebook.NotebookChild)(this.noteBookGameSettings[this.vbox3]));
			w43.Position = 2;
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Flatland");
			this.noteBookGameSettings.SetTabLabel (this.vbox3, this.label4);
			this.label4.ShowAll ();
			// Container child noteBookGameSettings.Gtk.Notebook+NotebookChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			this.vbox4.BorderWidth = ((uint)(6));
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("First Round Duration");
			this.hbox5.Add (this.label13);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label13]));
			w44.Position = 0;
			w44.Expand = false;
			w44.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.spinButtonGroupSumFirstRoundSeconds = new global::Gtk.SpinButton (1, 999, 1);
			this.spinButtonGroupSumFirstRoundSeconds.CanFocus = true;
			this.spinButtonGroupSumFirstRoundSeconds.Name = "spinButtonGroupSumFirstRoundSeconds";
			this.spinButtonGroupSumFirstRoundSeconds.Adjustment.PageIncrement = 10;
			this.spinButtonGroupSumFirstRoundSeconds.ClimbRate = 1;
			this.spinButtonGroupSumFirstRoundSeconds.Numeric = true;
			this.spinButtonGroupSumFirstRoundSeconds.Value = 10;
			this.hbox5.Add (this.spinButtonGroupSumFirstRoundSeconds);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.spinButtonGroupSumFirstRoundSeconds]));
			w45.Position = 1;
			w45.Expand = false;
			w45.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("second(s)");
			this.hbox5.Add (this.label14);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label14]));
			w46.Position = 2;
			w46.Expand = false;
			w46.Fill = false;
			this.vbox4.Add (this.hbox5);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox5]));
			w47.Position = 0;
			w47.Expand = false;
			w47.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Subsequent Round Duration");
			this.hbox6.Add (this.label15);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label15]));
			w48.Position = 0;
			w48.Expand = false;
			w48.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.spinButtonGroupSumRoundSeconds = new global::Gtk.SpinButton (1, 999, 1);
			this.spinButtonGroupSumRoundSeconds.CanFocus = true;
			this.spinButtonGroupSumRoundSeconds.Name = "spinButtonGroupSumRoundSeconds";
			this.spinButtonGroupSumRoundSeconds.Adjustment.PageIncrement = 10;
			this.spinButtonGroupSumRoundSeconds.ClimbRate = 1;
			this.spinButtonGroupSumRoundSeconds.Numeric = true;
			this.spinButtonGroupSumRoundSeconds.Value = 10;
			this.hbox6.Add (this.spinButtonGroupSumRoundSeconds);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.spinButtonGroupSumRoundSeconds]));
			w49.Position = 1;
			w49.Expand = false;
			w49.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("second(s)");
			this.hbox6.Add (this.label16);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label16]));
			w50.Position = 2;
			w50.Expand = false;
			w50.Fill = false;
			this.vbox4.Add (this.hbox6);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox6]));
			w51.Position = 1;
			w51.Expand = false;
			w51.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Number Range");
			this.hbox7.Add (this.label17);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label17]));
			w52.Position = 0;
			w52.Expand = false;
			w52.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.spinButtonGroupSumRangeStart = new global::Gtk.SpinButton (0, 8, 1);
			this.spinButtonGroupSumRangeStart.CanFocus = true;
			this.spinButtonGroupSumRangeStart.Name = "spinButtonGroupSumRangeStart";
			this.spinButtonGroupSumRangeStart.Adjustment.PageIncrement = 10;
			this.spinButtonGroupSumRangeStart.ClimbRate = 1;
			this.spinButtonGroupSumRangeStart.Numeric = true;
			this.hbox7.Add (this.spinButtonGroupSumRangeStart);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.spinButtonGroupSumRangeStart]));
			w53.Position = 1;
			w53.Expand = false;
			w53.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("* players to");
			this.hbox7.Add (this.label18);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label18]));
			w54.Position = 2;
			w54.Expand = false;
			w54.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.spinButtonGroupSumRangeEnd = new global::Gtk.SpinButton (1, 9, 1);
			this.spinButtonGroupSumRangeEnd.CanFocus = true;
			this.spinButtonGroupSumRangeEnd.Name = "spinButtonGroupSumRangeEnd";
			this.spinButtonGroupSumRangeEnd.Adjustment.PageIncrement = 10;
			this.spinButtonGroupSumRangeEnd.ClimbRate = 1;
			this.spinButtonGroupSumRangeEnd.Numeric = true;
			this.spinButtonGroupSumRangeEnd.Value = 9;
			this.hbox7.Add (this.spinButtonGroupSumRangeEnd);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.spinButtonGroupSumRangeEnd]));
			w55.Position = 3;
			w55.Expand = false;
			w55.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.Xalign = 0f;
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("* players");
			this.hbox7.Add (this.label19);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label19]));
			w56.PackType = ((global::Gtk.PackType)(1));
			w56.Position = 4;
			this.vbox4.Add (this.hbox7);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox7]));
			w57.Position = 2;
			w57.Expand = false;
			w57.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.checkButtonGroupSumNumericFeedback = new global::Gtk.CheckButton ();
			this.checkButtonGroupSumNumericFeedback.CanFocus = true;
			this.checkButtonGroupSumNumericFeedback.Name = "checkButtonGroupSumNumericFeedback";
			this.checkButtonGroupSumNumericFeedback.Label = global::Mono.Unix.Catalog.GetString ("Show numeric feedback");
			this.checkButtonGroupSumNumericFeedback.DrawIndicator = true;
			this.checkButtonGroupSumNumericFeedback.UseUnderline = true;
			this.vbox4.Add (this.checkButtonGroupSumNumericFeedback);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.checkButtonGroupSumNumericFeedback]));
			w58.Position = 3;
			w58.Expand = false;
			w58.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.checkbuttonGroupSumPreviousInput = new global::Gtk.CheckButton ();
			this.checkbuttonGroupSumPreviousInput.CanFocus = true;
			this.checkbuttonGroupSumPreviousInput.Name = "checkbuttonGroupSumPreviousInput";
			this.checkbuttonGroupSumPreviousInput.Label = global::Mono.Unix.Catalog.GetString ("Use input from previous round");
			this.checkbuttonGroupSumPreviousInput.DrawIndicator = true;
			this.checkbuttonGroupSumPreviousInput.UseUnderline = true;
			this.vbox4.Add (this.checkbuttonGroupSumPreviousInput);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.checkbuttonGroupSumPreviousInput]));
			w59.Position = 4;
			w59.Expand = false;
			w59.Fill = false;
			this.noteBookGameSettings.Add (this.vbox4);
			global::Gtk.Notebook.NotebookChild w60 = ((global::Gtk.Notebook.NotebookChild)(this.noteBookGameSettings[this.vbox4]));
			w60.Position = 3;
			// Notebook tab
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("page4");
			this.noteBookGameSettings.SetTabLabel (this.vbox4, this.label12);
			this.label12.ShowAll ();
			// Container child noteBookGameSettings.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			this.vbox5.BorderWidth = ((uint)(6));
			// Container child vbox5.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(12));
			// Container child table1.Gtk.Table+TableChild
			this.label21 = new global::Gtk.Label ();
			this.label21.Name = "label21";
			this.label21.Xalign = 0f;
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of Plots");
			this.table1.Add (this.label21);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table1[this.label21]));
			w61.XOptions = ((global::Gtk.AttachOptions)(4));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label22 = new global::Gtk.Label ();
			this.label22.Name = "label22";
			this.label22.Xalign = 0f;
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("Travel Time (seconds)");
			this.table1.Add (this.label22);
			global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.table1[this.label22]));
			w62.TopAttach = ((uint)(1));
			w62.BottomAttach = ((uint)(2));
			w62.XOptions = ((global::Gtk.AttachOptions)(4));
			w62.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.Xalign = 0f;
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("Food Rate (per second)");
			this.table1.Add (this.label23);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.table1[this.label23]));
			w63.TopAttach = ((uint)(2));
			w63.BottomAttach = ((uint)(3));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label24 = new global::Gtk.Label ();
			this.label24.Name = "label24";
			this.label24.Xalign = 0f;
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("Game Duration (minutes)");
			this.table1.Add (this.label24);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table1[this.label24]));
			w64.TopAttach = ((uint)(3));
			w64.BottomAttach = ((uint)(4));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spinButtonForagerFoodRate = new global::Gtk.SpinButton (1, 999, 1);
			this.spinButtonForagerFoodRate.CanFocus = true;
			this.spinButtonForagerFoodRate.Name = "spinButtonForagerFoodRate";
			this.spinButtonForagerFoodRate.Adjustment.PageIncrement = 10;
			this.spinButtonForagerFoodRate.ClimbRate = 1;
			this.spinButtonForagerFoodRate.Numeric = true;
			this.spinButtonForagerFoodRate.Value = 3;
			this.table1.Add (this.spinButtonForagerFoodRate);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table1[this.spinButtonForagerFoodRate]));
			w65.TopAttach = ((uint)(2));
			w65.BottomAttach = ((uint)(3));
			w65.LeftAttach = ((uint)(1));
			w65.RightAttach = ((uint)(2));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spinButtonForagerGameMinutes = new global::Gtk.SpinButton (1, 999, 1);
			this.spinButtonForagerGameMinutes.CanFocus = true;
			this.spinButtonForagerGameMinutes.Name = "spinButtonForagerGameMinutes";
			this.spinButtonForagerGameMinutes.Adjustment.PageIncrement = 10;
			this.spinButtonForagerGameMinutes.ClimbRate = 1;
			this.spinButtonForagerGameMinutes.Numeric = true;
			this.spinButtonForagerGameMinutes.Value = 2;
			this.table1.Add (this.spinButtonForagerGameMinutes);
			global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.table1[this.spinButtonForagerGameMinutes]));
			w66.TopAttach = ((uint)(3));
			w66.BottomAttach = ((uint)(4));
			w66.LeftAttach = ((uint)(1));
			w66.RightAttach = ((uint)(2));
			w66.XOptions = ((global::Gtk.AttachOptions)(4));
			w66.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spinButtonForagerPlots = new global::Gtk.SpinButton (2, 9, 1);
			this.spinButtonForagerPlots.CanFocus = true;
			this.spinButtonForagerPlots.Name = "spinButtonForagerPlots";
			this.spinButtonForagerPlots.Adjustment.PageIncrement = 10;
			this.spinButtonForagerPlots.ClimbRate = 1;
			this.spinButtonForagerPlots.Numeric = true;
			this.spinButtonForagerPlots.Value = 8;
			this.table1.Add (this.spinButtonForagerPlots);
			global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.table1[this.spinButtonForagerPlots]));
			w67.LeftAttach = ((uint)(1));
			w67.RightAttach = ((uint)(2));
			w67.XOptions = ((global::Gtk.AttachOptions)(4));
			w67.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spinButtonForagerTravelTime = new global::Gtk.SpinButton (1, 999, 1);
			this.spinButtonForagerTravelTime.CanFocus = true;
			this.spinButtonForagerTravelTime.Name = "spinButtonForagerTravelTime";
			this.spinButtonForagerTravelTime.Adjustment.PageIncrement = 10;
			this.spinButtonForagerTravelTime.ClimbRate = 1;
			this.spinButtonForagerTravelTime.Numeric = true;
			this.spinButtonForagerTravelTime.Value = 3;
			this.table1.Add (this.spinButtonForagerTravelTime);
			global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.table1[this.spinButtonForagerTravelTime]));
			w68.TopAttach = ((uint)(1));
			w68.BottomAttach = ((uint)(2));
			w68.LeftAttach = ((uint)(1));
			w68.RightAttach = ((uint)(2));
			w68.XOptions = ((global::Gtk.AttachOptions)(4));
			w68.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox5.Add (this.table1);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.table1]));
			w69.Position = 0;
			w69.Expand = false;
			w69.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox5.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hseparator2]));
			w70.Position = 1;
			w70.Expand = false;
			w70.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label ();
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("Probability Set");
			this.hbox8.Add (this.label25);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label25]));
			w71.Position = 0;
			w71.Expand = false;
			w71.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.comboBoxForagerProbabilitySet = global::Gtk.ComboBox.NewText ();
			this.comboBoxForagerProbabilitySet.Name = "comboBoxForagerProbabilitySet";
			this.hbox8.Add (this.comboBoxForagerProbabilitySet);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.comboBoxForagerProbabilitySet]));
			w72.Position = 1;
			w72.Expand = false;
			w72.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.buttonForagerAddProbabilitySet = new global::Gtk.Button ();
			this.buttonForagerAddProbabilitySet.CanFocus = true;
			this.buttonForagerAddProbabilitySet.Name = "buttonForagerAddProbabilitySet";
			this.buttonForagerAddProbabilitySet.UseStock = true;
			this.buttonForagerAddProbabilitySet.UseUnderline = true;
			this.buttonForagerAddProbabilitySet.Label = "gtk-add";
			this.hbox8.Add (this.buttonForagerAddProbabilitySet);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.buttonForagerAddProbabilitySet]));
			w73.Position = 2;
			w73.Expand = false;
			w73.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.buttonForagerRemoveProbabilitySet = new global::Gtk.Button ();
			this.buttonForagerRemoveProbabilitySet.CanFocus = true;
			this.buttonForagerRemoveProbabilitySet.Name = "buttonForagerRemoveProbabilitySet";
			this.buttonForagerRemoveProbabilitySet.UseStock = true;
			this.buttonForagerRemoveProbabilitySet.UseUnderline = true;
			this.buttonForagerRemoveProbabilitySet.Label = "gtk-remove";
			this.hbox8.Add (this.buttonForagerRemoveProbabilitySet);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.buttonForagerRemoveProbabilitySet]));
			w74.Position = 3;
			w74.Expand = false;
			w74.Fill = false;
			this.vbox5.Add (this.hbox8);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox8]));
			w75.Position = 2;
			w75.Expand = false;
			w75.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label26 = new global::Gtk.Label ();
			this.label26.Name = "label26";
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("Use this probability set after");
			this.hbox12.Add (this.label26);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.label26]));
			w76.Position = 0;
			w76.Expand = false;
			w76.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.spinButtonForagerProbabilityShiftMinutes = new global::Gtk.SpinButton (1, 999, 1);
			this.spinButtonForagerProbabilityShiftMinutes.Sensitive = false;
			this.spinButtonForagerProbabilityShiftMinutes.CanFocus = true;
			this.spinButtonForagerProbabilityShiftMinutes.Name = "spinButtonForagerProbabilityShiftMinutes";
			this.spinButtonForagerProbabilityShiftMinutes.Adjustment.PageIncrement = 10;
			this.spinButtonForagerProbabilityShiftMinutes.ClimbRate = 1;
			this.spinButtonForagerProbabilityShiftMinutes.Numeric = true;
			this.spinButtonForagerProbabilityShiftMinutes.Value = 1;
			this.hbox12.Add (this.spinButtonForagerProbabilityShiftMinutes);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.spinButtonForagerProbabilityShiftMinutes]));
			w77.Position = 1;
			w77.Expand = false;
			w77.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label27 = new global::Gtk.Label ();
			this.label27.Name = "label27";
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString ("minute(s)");
			this.hbox12.Add (this.label27);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.label27]));
			w78.Position = 2;
			w78.Expand = false;
			w78.Fill = false;
			this.vbox5.Add (this.hbox12);
			global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox12]));
			w79.Position = 3;
			w79.Expand = false;
			w79.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeViewForagerProbabilities = new global::Gtk.TreeView ();
			this.treeViewForagerProbabilities.CanFocus = true;
			this.treeViewForagerProbabilities.Name = "treeViewForagerProbabilities";
			this.GtkScrolledWindow1.Add (this.treeViewForagerProbabilities);
			this.vbox5.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.GtkScrolledWindow1]));
			w81.Position = 4;
			this.noteBookGameSettings.Add (this.vbox5);
			global::Gtk.Notebook.NotebookChild w82 = ((global::Gtk.Notebook.NotebookChild)(this.noteBookGameSettings[this.vbox5]));
			w82.Position = 4;
			// Notebook tab
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("page5");
			this.noteBookGameSettings.SetTabLabel (this.vbox5, this.label20);
			this.label20.ShowAll ();
			this.vbox2.Add (this.noteBookGameSettings);
			global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.noteBookGameSettings]));
			w83.Position = 2;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(w1[this.vbox2]));
			w84.Position = 0;
			// Internal child Nexus.DialogNewGame.ActionArea
			global::Gtk.HButtonBox w85 = this.ActionArea;
			w85.Name = "dialog1_ActionArea";
			w85.Spacing = 6;
			w85.BorderWidth = ((uint)(5));
			w85.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w86 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w85[this.buttonCancel]));
			w86.Expand = false;
			w86.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.Sensitive = false;
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w87 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w85[this.buttonOk]));
			w87.Position = 1;
			w87.Expand = false;
			w87.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 495;
			this.DefaultHeight = 468;
			this.Show ();
			this.comboBoxGame.Changed += new global::System.EventHandler (this.OnComboBoxGameChanged);
			this.spinButtonPixelMaxSize.ValueChanged += new global::System.EventHandler (this.OnSpinButtonPixelMaxSizeValueChanged);
			this.checkBoxFlatlandCustomBoardSize.Toggled += new global::System.EventHandler (this.OnCheckBoxFlatlandCustomBoardSizeToggled);
			this.buttonFlatlandEditFixedTiles.Clicked += new global::System.EventHandler (this.buttonFlatlandEditFixedTiles_Clicked);
			this.buttonFlatlandClearTeams.Clicked += new global::System.EventHandler (this.OnButtonFlatlandClearTeamsClicked);
			this.buttonFlatlandRemoveTeam.Clicked += new global::System.EventHandler (this.OnButtonFlatlandRemoveTeamClicked);
			this.buttonFlatlandAddTeam.Clicked += new global::System.EventHandler (this.OnButtonFlatlandAddTeamClicked);
			this.spinButtonForagerPlots.ValueChanged += new global::System.EventHandler (this.OnSpinButtonForagerPlotsValueChanged);
			this.comboBoxForagerProbabilitySet.Changed += new global::System.EventHandler (this.OnComboBoxForagerProbabilitySetChanged);
			this.buttonForagerAddProbabilitySet.Clicked += new global::System.EventHandler (this.OnButtonForagerAddProbabilitySetClicked);
			this.buttonForagerRemoveProbabilitySet.Clicked += new global::System.EventHandler (this.OnButtonForagerRemoveProbabilitySetClicked);
			this.spinButtonForagerProbabilityShiftMinutes.ValueChanged += new global::System.EventHandler (this.OnSpinButtonForagerProbabilityShiftMinutesValueChanged);
		}
	}
}
